import { NextResponse } from "next/server";
import { buildOpenApi } from "../../../../lib/api/openapi";
import { auth } from "../../../../server/auth";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

type Doc = {
  paths?: Record<string, unknown>;
  tags?: { name: string; description?: string }[];
  components?: { schemas?: Record<string, unknown>; securitySchemes?: Record<string, unknown> };
};

/**
 * The API description (OpenAPI 3.1): our own routes, plus every endpoint of the sign-in system (sign-up and sign-in, sessions,
 * passkeys, usernames, email codes, admin) generated by the auth library so it always matches what is installed.
 * Set API_DOCS=off to hide it in an environment where it should not be public.
 */
export async function GET() {
  if (process.env.API_DOCS?.trim().toLowerCase() === "off") return NextResponse.json({ error: "Not found." }, { status: 404 });
  const ours = buildOpenApi() as unknown as Doc & Record<string, unknown>;
  try {
    const theirs = (await (auth.api as unknown as { generateOpenAPISchema: () => Promise<Doc> }).generateOpenAPISchema()) as Doc;
    const merged: Record<string, unknown> = { ...(ours.paths ?? {}) };
    // Our hand-written entries for the few auth endpoints give way to the generated, complete ones.
    for (const k of Object.keys(merged)) if (k.startsWith("/api/auth/")) delete merged[k];
    for (const [p, v] of Object.entries(theirs.paths ?? {})) merged[p.startsWith("/api/") ? p : `/api/auth${p}`] = v;
    ours.paths = merged;
    ours.components = {
      schemas: { ...(theirs.components?.schemas ?? {}), ...(ours.components?.schemas ?? {}) },
      securitySchemes: { ...(theirs.components?.securitySchemes ?? {}), ...(ours.components?.securitySchemes ?? {}) },
    };
    const names = new Set((ours.tags ?? []).map((t) => t.name));
    ours.tags = [...(ours.tags ?? []), ...(theirs.tags ?? []).filter((t) => !names.has(t.name))];
  } catch {
    /* the auth description is a bonus: if it cannot be generated, the app's own routes are still served */
  }
  return NextResponse.json(ours, { headers: { "cache-control": "no-store" } });
}
